### ISSUE TITLE
cannot create lemp server with wordpress

### ISSUE THREAD

**Issue by wp-coin** [lando/wordpress#35]
docker.errors.DockerException: Credentials store error: StoreError('Unexpected OS error "Exec format error", errno=8')
ERROR ==>  message=, stack=Error
    at /home/brody/lando-cli/node_modules/@lando/core/lib/shell.js:158:44

**Comment by reynoldsalec** [comment]
@wp-coin I'm not exactly sure on the context of the error; if you have more details (steps taken to get to this point) etc. LMK, know this is fairly stale so I'll close it out for the time being, but definitely comment here and we can re-open to figure it out!
