### ISSUE TITLE
automate Download WordPress and setup wp-config.php

### ISSUE THREAD

**Issue by helgatheviking** [lando/wordpress#5]
Could the recipe download WordPress and set up the wp-config.php automatically on `lando start` to make the spinup process even simplier for new users?

**Comment by gitressa** [comment]
It doesn't automate the set up, but the PR https://github.com/lando/wordpress/pull/6 adds commands to [gettting-started.md](https://github.com/lando/wordpress/blob/e586a677b8a1276235cf3d7ac9dbf928057d22e5/docs/getting-started.md) for quick creation of config file and installation via the command line.

**Comment by labboy0276** [comment]
It would be difficult to automate the setup of wp-config.php as WordPress now has numerous different ways to use WordPress (i.e vanilla, BedRock, composer only, various hosting provider setups, etc).  So with that, It is really up to the user due to this complexity.
