### ISSUE TITLE
Change to mysql:8.0 in .lando.yml pulls "MySQL version 15.1 Distrib 10.5.23-MariaDB"

### ISSUE THREAD

**Issue by martisj** [lando/wordpress#70]
This is my `.lando.yml`
```yml
name: kiropraktorgruppen-dev
recipe: wordpress
config:
    webroot: wordpress
    php: '8.0'
    via: apache:2.4
    database: mysql:8.0
```

When I run `lando start` I get this output:
```
OS:     Linux 6.8.8-1-default #1 SMP PREEMPT_DYNAMIC Mon Apr 29 05:24:46 UTC 2024 (5cd3298) x86_64
Shell:
PHP binary:     /usr/local/bin/php
PHP version:    8.0.30
php.ini used:
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 15.1 Distrib 10.5.23-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /app
WP-CLI packages dir:
WP-CLI cache dir:       /var/www/.wp-cli/cache
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.10.0
[+] Stopping 1/1
 ✔ Container kiropraktorgruppendev_appserver_1  Sto...                                              10.7s
[+] Running 2/2
 ✔ Container kiropraktorgruppendev_appserver_1  Sta...                                               0.0s
 ✔ Container kiropraktorgruppendev_database_1   Star...                                              0.1s
[+] Healthchecking 1/1
 ✔ Healthcheck kiropraktorgruppendev_database_1  Passed
```

First I tried running `lando db-import` on a db dump from a MySQL version 8.0 and read that the default version of MySQL for the WordPress recipe (and Lando for that matter is 5.7).
The output from `lando db-import 20240512_wp_db.sql`:
```
❯ lando db-import 20240512_wp_db.sql
Preparing to import /app/20240512_wp_db.sql into database 'wordpress' on service 'database' as user root...

Emptying wordpress...
NOTE: See the --no-wipe flag to avoid this step!
Importing /app/20240512_wp_db.sql...
ERROR 1067 (42000) at line 14: Invalid default value for 'comment_date'
Import failed.
```
Not sure if this a bug or an issue with my configuration. Input mucho appreciated :hugs:

**Comment by AaronFeledy** [comment]
The initial output you're seeing is from WP-CLI which is showing the version of the `mysql` command line tool rather than the version of the database. The mariadb variety of the `mysql` command is installed in the appserver container by default, so that's what you're seeing there. Lando is still pulling the correct image. You should be able to verify that by running `docker ps`.

For your import error, it looks like there might be invalid data in your db dump. You might be able to work around this with this command: `lando ssh -c "mysql --host=database -u wordpress --database=wordpress -pwordpress -e 'SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";'"`

**Comment by martisj** [comment]
Wowee! Thank you @AaronFeledy :pray:. The database server is indeed `mysql:8.0`. However the ssh command didn't work with the db-import. What did work was "dumping" the database with `mysqldump` instead of wp-cli's: `wp search-replace --path="$HOME/public_html" 'https://example.com' 'https://mewordpress.site.com' --recurse-objects --skip-columns=guid --skip-tables=wp_users --export="$wp_db_file"`

**Comment by martisj** [comment]
Not sure why that doesn't work though.

**Comment by martisj** [comment]
Hmm, forgot to close.
